#pragma once

#include "NativeGameplayTags.h"

namespace PargonGameplayAbilityTag
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BasicAttack)
}

namespace PargonGameplayEventTag
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_HitDetection)

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ComboChange_End)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ComboChange_Combo01)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ComboChange_Combo02)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ComboChange_Combo03)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ComboChange_Combo04)
}